### ISSUE TITLE
Unexpected lighting behavior

### ISSUE THREAD

**Issue by VirusNik21** [Eligarf/stealthy#144]
Hello.
For some reason the light behavior works differently in the Stealth and Token Light Condition module.

In this example (see the Overview img): 

1) Global Illumibation is disabled on the scene. Token Light Condition Global Illumibation setting is also off.

2) A light source is placed above the scene at a height of 30 ft.

3) A 3 x 3 cell building is placed with a roof blocking the light above itself and a window in which the light enters (a separate source near the house, to create the effect of rays entering inside). Had to use this method because rooftops cannot block light from global illumination, but only from sources on the stage above themselves.

4) Inside it is placed a region with behavior: darkness level setting (to create the effect of a shaded room under the roof).

As a result Token Light Condition correctly determines the shading inside - Dim or Dark depending on the proximity to the window, and Stealthy always sees only Bright from the light from point (2). 
(see the img HUD)

![HUD](https://github.com/Eligarf/stealthy/assets/150345729/51ddaa2f-e20e-44be-8b64-034ea55073cb)
![Overview](https://github.com/Eligarf/stealthy/assets/150345729/01eff959-3dfd-43ae-a777-e395c36a01be)

**Comment by Eligarf** [comment]
I'll have to figure out regions to get this to work. It's on the queue.

**Comment by Eligarf** [comment]
If I put a token in a darkened area without GI, it picks up whatever lighting affects that area, as if the darkened region wasn't even present - it seems to only be an aesthetic styling for the background. If I enable GI, that darkened area suddenly works as expected and the token is not visible to others without darkvision. I'm having trouble exactly reproducing the light and roof arrangement you describe, so if you could show me more precise settings or send me a minimal scene with the setting you use that would be helpful.

**Comment by VirusNik21** [comment]
Yes, i'll do it tomorow

**Comment by VirusNik21** [comment]
https://drive.google.com/file/d/1OVzTTudSVNn0_9muRsk1NAomxEvN6Dx6/view?usp=sharing
link to the archive with test world.

Modules:
![image](https://github.com/Eligarf/stealthy/assets/150345729/787962fe-7c2a-4eb4-acc9-97bbd5cd82e6)

**Comment by Eligarf** [comment]
Thanks for the level, I appreciate your attention to detail here!

What we have here is a fight between what we expect darkened to do and what Foundry actually does in the vision/lighting engine. TLC is applying the dark condition as you intend, but Foundry's vision system is doing something else entirely. I moved Рэндал on the map north of the building, as they don't have darkvision, and put Сефрис in the center of the building instead. I then changed the little wall section into a window by removing sight restrictions. Рэндал was able to see Сефрис according to the lighting engine. I then adjusted the Sun Light source to be wall constrained, and Рэндал was no longer able to see Сефрис.

Stealthy is trying to work within the behavior of the Foundry vision system. When Рэндал can't see Сефрис because the sunlight is wall constrained, Stealthy shows Сефрис being in dark because that is what Foundry's lighting engine thinks. When using unconstrained sunlight, the Foundry vision system lets Рэндал see Сефрис, and Stealthy shows Сефрис being in bright light, again as Foundry thinks. TLC has done some aspirational code that uses the darkness in the way you intend, but it actually kind of a bug since it doesn't match the Foundry engine unless TLC were to modify the engine's behavior. As far as I can tell, without GI the only practical use for darkness level is to turn on/off lights.

I wish I had a better answer for you, but tackling changes to the lighting engine is outside Stealthy's scope. I'm still quite clueless on how to use elevated tiles to block lights - even on your level I can't see any effect from that roof on the lighting state of tokens under it. I tried removing the walls and wall constraining the sunlight so that it would be affected by the roof, but nothing changed.

**Comment by VirusNik21** [comment]
Thank you. That's about what I was thinking as I've noticed the difference in performance between the TLC and core FVTT. Thanks anyway) I will keep these limitations in mind.
