### ISSUE TITLE
Suggestion : add an option to disable light check for token

### ISSUE THREAD

**Issue by R0TEAM** [Eligarf/stealthy#150]
The modul is realy excellent !
But one thing bother me .... if i have an snake hidden in an bush ... in full sunlight ... he is not realy hidden ...
So i like to set the hidden effect of the snake (or other tokens) to ignore light conditions...

**Comment by Eligarf** [comment]
Thanks!

What system are you using? As for a snake hidden in a bush in daylight, I would think you can just bank a stealth check for that snake ahead of time, and even adjust it using the token HUD to make it difficult to detect. If a non-allied token tries to see it, it will need to beat that stealth check with its banked perception roll or passive value in order to be visible as far as Stealthy is concerned.

If you just add the hidden (or Hiding depending on system) condition to the token without doing a stealth check, it will use the passive stealth score instead.

**Comment by R0TEAM** [comment]
DnD5e
I would prefer an option to exclude tokens from light check ....
Set the  stealth value higher as it should, can have unwanted side effects ....

**Comment by Eligarf** [comment]
Stealthy uses the foundry light engine to know the light condition, and only distinguishes between bright and dim, as things in darkness have already been removed by the engine itself. Are you meaning to give the PCs disadvantage to spot the thing, or are you wanting a locallized darkness area? Both of these are things done by either Core or Midi. I would need more context and explanation to see how what you want fits in with the narrow scope I hold for Stealthy.
