### ISSUE TITLE
Problems with different Languages from Host<>Client

### ISSUE THREAD

**Issue by R0TEAM** [Eligarf/stealthy#157]
If the languags settings differ from the Host to the client (Host German <> Client English) then on client side, tokens are visible because the right keyword is missing .... (expecting keyword in diff language)

**Comment by Eligarf** [comment]
The effect object I'd be looking at on the client doesn't have any term that is fixed to mean hidden regardless of language. It might be possible to do in the case where you have Stealthy configured to use the built-in hiding condition, because I believe I would get a status trait for hiding that remains the same regardless of language. Other than that, all I could do is maybe add multiple words to search for when looking for hidden.

**Comment by Eligarf** [comment]
Added an alias field in the settings in 4.9.0
