### ISSUE TITLE
[Feature Request] Breaking Stealth

### ISSUE THREAD

**Issue by btbias** [Eligarf/stealthy#23]
Absolutely love this module! I think what would make it more convenient is if a creature's "hidden" effect could be automatically removed when that creature attacks, uses a spell, etc. That should be accurate to 5e's stealth rules, and it's easier than manually deleting the effect from your character (which rogues would be doing often as they attack and sneak again repeatedly).

Perhaps this could be a setting you could enable/disable so that you don't _have_ to have this behavior enabled as well, since not everyone will want this automated for them.

Cheers!

**Comment by Eligarf** [comment]
Thanks for the feedback, I'm glad you like it! I'm trying to keep this module extremely focused and limited to the behavior of stealth itself, and am purposely leaving the issue of when it should drop to other modules. Midi-QOL is what I use for this purpose (the name 'Hidden' was chosen to be compatible with its behavior), but perhaps some other module might serve this purpose. I will keep your comments in mind for future developments though.

**Comment by Eligarf** [comment]
Also, I look briefly at it this morning and stumbled across the Skulker feat which lets you keep stealth with a missed ranged attack, so heavier automation frameworks are absolutely required for this to be automated. And I don't want get anywhere near "what happens if I lose cover/concealment?" etc. So meat-tech will have to handle this. :)
