### ISSUE TITLE
Request: make Spot optional, or expire out of combat too

### ISSUE THREAD

**Issue by dmaneyapanda** [Eligarf/stealthy#26]
Awesome mod.  I love it.

One or maybe two related requests.  I appreciate the Perception roll creating a spot effect, but I am having trouble with it being a little overused.  I use perception checks a lot in my campaign (usually every time they are searching for secret doors, searching for loot, etc.), and now each time one of them rolls they get this little Spot active effect, which isn't really related to spotting a hidden enemy. 

Moreover, the Spot effect goes on with a duration of 1 turn, but since we're out of combat, that actually never triggers, and the effect stays on indefinitely (or until the next time we go into combat at least).  I haven't fully tested this without other mods to make sure it's repeatable, but based on previous experience I think this is what's happening.

So ideally there might be some settings to help control this.  Some ideas:
1- An option to just not do the Spot stuff at all - in case we want to handle it manually
2- An option for Spot to only get added in combat
3- Some better expiration conditions for it, to accommodate both 1 turn (which I think you probably just picked arbitrarily, it's not RAW anywhere is it?), or something like 6 or 10 second passing.  I seem to recall this was a problem in Midi though, it would only ever expire on one or the other, not both a round duration or a time duration.  Maybe this is no longer the case though.

Thanks!

**Comment by Eligarf** [comment]
Adding both a time and turn duration is easy enough - it certainly isn't from RAW but is an approximation that seems to work well in my games. Having the active spot only apply during combat doesn't handle the scouting case (I wrote this module because I was playing a gloom stalker and was tired of the handwaving about who saw who), and having the active spot skill is important if you want that chance to spot folks before the combat kicks off.

That being said, perhaps the simplest solution is adding a dynamic control to token controls on the left that enables/disables adding the spot condition? I'll have to poke about other modules to see examples of doing that.
