### ISSUE TITLE
Umbral Sight Token being detected when it has the Dark Active Effect when any amount of light overlaps the token

### ISSUE THREAD

**Issue by tnarv** [Eligarf/stealthy#87]
Here's a screen shot showing a creature (the zombie looking dude) and my gloomstalker ranger player. 

![image](https://user-images.githubusercontent.com/75012229/215224580-3641af44-ea16-405d-8fd5-01c11c8bbe01.png)

The token has the "Dark" active effect (from Token Light Condition) and Umbral Sight feature so it should be imperceptible I think.

There's a tiny bit of dim light overlapping the token which I think is triggering Basic Sight to say the token is detectable. 

If I move the token just out of the range of the light things work as they should

Token moved out of light source range
![image](https://user-images.githubusercontent.com/75012229/215225106-69d3964d-a977-4f9b-9cef-eb0dcd8a2dde.png)

Zombie boyo can longer see Ranger
![image](https://user-images.githubusercontent.com/75012229/215225217-86737066-23d2-4007-93dc-ec70cf765ba3.png)

**Comment by Eligarf** [comment]
This isn't quite as simple as it sounds. I could add an option for gloomstalkers to check for the 'dark' effect against darkvision, but a larger problem remains that any other token standing in that spot would also be visible even though it has the 'dark' effect. I'm trying to keep Stealthy as focused as possible, and it only plays in the space of skill rolls rather than looking for lights/etc. For this case, I'd actually suggest that TLC take over determining if something is visible or not due to light conditions. They could hook into the visibility chain and reject things in darkness/etc, then Stealthy just does skill rejects on the remaining tokens.
